version: 0.0
os: linux
files:
  - source: /
    destination: /opt/bookmyshow
hooks:
  ApplicationStop:
    - location: stop_server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: ec2-user