version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 18
  build:
    commands:
      # 1. Build Spring Boot Backend (Maven)
      - cd backend
      - chmod +x mvnw  # <-- This fixes the "Permission denied" error!
      - ./mvnw clean package -DskipTests
      - cd ..
        
      # 2. Build React Frontend
      - cd frontend
      # Fetch the ALB DNS Name dynamically
      - ALB_DNS=$(aws elbv2 describe-load-balancers --names bookmyshow-alb --query "LoadBalancers[0].DNSName" --output text --region us-east-1)
      - echo "VITE_BACKEND_API=http://$ALB_DNS" > .env
      - npm install
      - npm run build
      - cd ..
      
  post_build:
    commands:
      # 3. Deploy frontend to S3
      # NOTE: If using Create React App, change 'dist/' to 'build/' below
      - aws s3 sync frontend/dist/ s3://bookmyshow-stack-frontendbucket-3mdev7qp7f6x --delete

artifacts:
  files:
    # 4. Correct artifact path for Maven target folder
    - backend/target/*.jar
    - appspec.yml
    - scripts/*
  discard-paths: yes