version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 18
  build:
    commands:
      # 1. Build Spring Boot Backend (Maven)
      - cd backend
      - chmod +x mvnw
      - ./mvnw clean package -DskipTests
      - cd ..
        
      # 2. Build React Frontend
      - cd frontend
      # Fetch the ALB DNS Name dynamically
      - ALB_DNS=$(aws elbv2 describe-load-balancers --names bookmyshow-alb --query "LoadBalancers[0].DNSName" --output text --region us-east-1)
      - echo "VITE_BACKEND_API=http://$ALB_DNS" > .env
      - npm install
      - npm run build
      - cd ..
      
  post_build:
    commands:
      # 3. 🌟 DYNAMIC S3 DEPLOYMENT 🌟
      # Now AWS automatically knows which bucket to use!
      - aws s3 sync frontend/dist/ s3://$FRONTEND_BUCKET --delete

artifacts:
  files:
    - backend/target/*.jar
    - appspec.yml
    - scripts/*
  discard-paths: yes